This notebook will create a desciptive statistics dataset for all players 4 targets.

In [1]:
import numpy as np
import pandas as pd
from numpy import mean,std
from scipy.stats import norm
import statistics as st

import os
import gc

import matplotlib.pyplot as plt
import seaborn as sns
import json

In [3]:
nextDayPlayerEngagement = pd.read_pickle('data/target_v/nextDayPlayerEngagement_train.pkl')
nextDayPlayerEngagement.head()

,engagementMetricsDate,playerId,target1,target2,target3,target4,index,date
0,2018-01-02,628317,0.011167,4.474708,0.005168,5.735294,0,20180101
1,2018-01-02,547989,0.042993,5.593385,0.045033,2.794118,0,20180101
2,2018-01-02,519317,0.974327,56.177043,13.693746,64.166667,0,20180101
3,2018-01-02,607625,0.006700,2.675097,0.005168,1.862745,0,20180101
4,2018-01-02,592547,0.001117,0.632296,0.002953,0.931373,0,20180101

In [4]:
nextDayPlayerEngagement['year'] = pd.DatetimeIndex(nextDayPlayerEngagement['engagementMetricsDate']).year
nextDayPlayerEngagement['month'] = pd.DatetimeIndex(nextDayPlayerEngagement['engagementMetricsDate']).month

In [14]:
new_df = nextDayPlayerEngagement[nextDayPlayerEngagement['year'] == 2020]
new_df = new_df[new_df['month'] >= 4]
new_df

,engagementMetricsDate,playerId,target1,target2,target3,target4,index,date,year,month
1690020,2020-04-01,519443,0.023018,2.282454,0.007664,1.140125,820,20200331,2020,4
1690021,2020-04-01,670370,1.519220,0.570613,0.093888,0.000000,820,20200331,2020,4
1690022,2020-04-01,518692,1.734060,7.037565,29.289136,8.127988,820,20200331,2020,4
1690023,2020-04-01,448306,0.015346,0.475511,0.005748,4.376609,820,20200331,2020,4
1690024,2020-04-01,649557,0.069055,1.521636,0.001916,1.728577,820,20200331,2020,4
...,...,...,...,...,...,...,...,...,...,...
2256790,2020-12-31,518748,0.000000,0.184247,0.000000,0.228013,1094,20201230,2020,12
2256791,2020-12-31,596720,0.000000,0.138185,0.000000,0.146580,1094,20201230,2020,12
2256792,2020-12-31,571437,0.000539,0.184247,0.000000,0.407166,1094,20201230,2020,12
2256793,2020-12-31,640464,0.000000,0.230309,0.000000,0.179153,1094,20201230,2020,12
2256794,2020-12-31,622682,0.204655,0.967296,0.000000,0.146580,1094,20201230,2020,12

In [11]:
playerId_list=new_df.playerId.unique().tolist()
#playerId_list=playerId_list[:10]
#playerId_list

In [15]:
import warnings
warnings.simplefilter('ignore')

def calc_probs(pid,df,temp):
    to_append=[pid,'','','','','','','','','','','','','','','','','','','','','','','','']
    targets=['target1','target2','target3','target4']
    z=1
    for target in targets:
        target_prob = temp[target].tolist()
        mean = np.mean(target_prob)
        std = np.std(target_prob)
        median = st.median(target_prob)
        distribution = norm(mean, std)
        min_weight = min(target_prob)
        max_weight = max(target_prob)
        values = list(np.linspace(min_weight, max_weight))
        probabilities = [distribution.pdf(v) for v in values]
        max_value = max(probabilities)
        max_index = probabilities.index(max_value)
        to_append[z]=mean
        to_append[z+1]=median
        to_append[z+2]=std
        to_append[z+3]=min_weight
        to_append[z+4]=max_weight
        to_append[z+5]=target_prob[max_index]
        z=z+6
    df_length = len(df)
    df.loc[df_length] = to_append
    return df
    

### CREATE DATAFRAME to store probabilities
column_names = ["playerId", "target1_mean","target1_median","target1_std","target1_min","target1_max","target1_prob", "target2_mean","target2_median","target2_std","target2_min","target2_max","target2_prob", "target3_mean","target3_median","target3_std","target3_min","target3_max","target3_prob", "target4_mean","target4_median","target4_std","target4_min","target4_max","target4_prob"]
player_target_probs = pd.DataFrame(columns = column_names)
    
for pid in playerId_list:
    temp = new_df[new_df['playerId'] == pid]
    player_target_stats=calc_probs(pid,player_target_probs,temp)

player_target_stats

,playerId,target1_mean,target1_median,target1_std,target1_min,target1_max,target1_prob,target2_mean,target2_median,target2_std,...,target3_std,target3_min,target3_max,target3_prob,target4_mean,target4_median,target4_std,target4_min,target4_max,target4_prob
0,502210.0,0.542648,0.046443,2.330427,0.002278,29.619097,0.063575,3.365974,2.747048,2.722890,...,2.604768,0.000581,40.624795,0.024909,1.774379,1.162948,1.753415,0.097241,10.147059,1.299767
1,630105.0,0.838659,0.045984,2.759595,0.000000,31.854782,0.000000,5.845361,3.616352,6.929367,...,3.118401,0.000000,25.667039,0.029934,1.812108,0.432725,3.632594,0.020560,37.695485,0.282220
2,621532.0,0.215140,0.004907,2.261577,0.000000,36.609660,0.007673,1.317950,0.937500,1.685209,...,0.003228,0.000000,0.025343,0.000791,0.276682,0.090648,0.634240,0.006533,4.844432,0.123457
3,468504.0,0.010297,0.001766,0.022914,0.000000,0.156740,0.042472,1.710889,0.811688,2.424050,...,1.056333,0.000000,15.652497,0.007001,0.408757,0.240906,0.645795,0.015244,7.835309,0.658514
4,657108.0,0.794021,0.130141,2.180669,0.000847,23.313692,0.303383,4.610821,3.940217,3.751572,...,5.227891,0.036260,59.370332,27.744961,0.663460,0.393771,0.828928,0.018581,6.180394,4.178385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,606944.0,0.000415,0.000000,0.002938,0.000000,0.032911,0.000000,1.260318,0.283575,1.692390,...,0.006565,0.000000,0.046019,0.003165,0.144759,0.083183,0.183682,0.003849,1.922127,0.137174
2057,620982.0,0.000495,0.000000,0.004150,0.000000,0.063708,0.000000,0.287233,0.022413,0.693790,...,0.003139,0.000000,0.049646,0.000000,0.112018,0.050365,0.376910,0.000000,5.246065,0.032776
2058,462480.0,0.000128,0.000000,0.001239,0.000000,0.015835,0.000000,0.066015,0.003779,0.127023,...,0.001144,0.000000,0.012530,0.000000,0.085188,0.052445,0.095623,0.000000,0.653310,0.020560
2059,667465.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.557464,0.283152,0.784526,...,0.285572,0.000000,3.009193,0.000000,0.070657,0.021918,0.208987,0.000000,2.651667,0.098328
2060,664852.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078346,0.003425,0.176020,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [16]:
player_target_stats.to_csv('data/player_target_stats_2020.csv', index = False)